name: Test cl-uniquifier on GNU CLisp
run-name: ${{ github.actor }} is testing cl-uniquifier on GNU CLisp
on: [push]
jobs:
  Test-cl-uniquifier-on-sbcl:
    runs-on: ubuntu-latest
    steps:
      - name: Install Clisp
        run: sudo apt-get install -y clisp
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: mkdir -p ../common-lisp
      - run: cp -r ../cl-uniquifier ../common-lisp/
      - name: Download dependency Alexandria
        run: cd ../common-lisp && git clone https://github.com/keithj/alexandria
      - name: Download dependency trivial-features
        run: cd ../common-lisp && git clone https://github.com/trivial-features/trivial-features
      - name: Download dependency trivial-garbage
        run: cd ../common-lisp && git clone https://github.com/trivial-garbage/trivial-garbage
      - name: Download dependency trivial-backtrace
        run: cd ../common-lisp && git clone https://github.com/hraban/trivial-backtrace
      - name: Download dependency asdf-flv
        run: cd ../common-lisp && git clone https://github.com/didierverna/asdf-flv
      - name: Download dependency global-vars
        run: cd ../common-lisp && git clone https://github.com/lmj/global-vars
      - name: Download dependency bordeaux-threads
        run: cd ../common-lisp && git clone https://github.com/sionescu/bordeaux-threads
      - name: Download dependency fiveam
        run: cd ../common-lisp && git clone https://github.com/lispci/fiveam
      - name: Get ASDF
        run: curl -O https://common-lisp.net/project/asdf/archives/asdf.lisp
      - name: Show me ASDF
        run: cat asdf.lisp
      - name: Run tests
        run: clisp -i asdf.lisp gh-workflow-runtests.lisp
      - run: echo "🍏 This job's status is ${{ job.status }}."
